### ISSUE TITLE
Filter failure: PRICE_FILTER

### ISSUE THREAD

**Issue by GO1984** [Roibal/Cryptocurrency-Trading-Bots-Python-Beginner-Advance#2]
While executing (Ubuntu 18.04 VM) Private_TriArbBot.py i get:

`
raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Filter failure: PRICE_FILTER`

It seems, that the currencies are mixed up and the price is ist not correct. 
The bot want to buy BNBBTC  @ 640.984552 insted of  0.00158 as of today
640.984552 is the price of ETH/USDT

Does anyone else have this problem?

**Comment by Roibal** [comment]
hello GO, yes I believe I have this part in error, and was dividing 1/price instead of price (which is why they are opposite, etc). I believe I have this fixed on a new version, I thought this version had the updated price.

**Comment by GO1984** [comment]
Thank you. I look all day for the error, but can't find it. Any chance you point me to the right line in the code to change?

**Comment by Roibal** [comment]
Line ~324. 

I just looked and I have uploaded newest version of tri arb bot--includes paper trading and output to social media.

**Comment by Roibal** [comment]
check out triarbbot_paper_and_tweet.py

**Comment by GO1984** [comment]
Thank you for sharing you work. I will report, if everything works well...

**Comment by Roibal** [comment]
it may be better if you report if everything doesn't work well, ha ha!

**Comment by GO1984** [comment]
Just to give an info. I have given up. I got lots of errors such as min_notional errors from the exchange and others. Nevertheless thank you for sharing. Your code gave me lots of ideas how to program in python.

**Comment by Roibal** [comment]
Yes, the Min_Notional comes direct from Binance, and requires a certain order volume, value, etc. Previously, Binance required all Binance Coins to be bought/sold in whole binance coins--you can imagine the headache this has caused! Luckily, they dropped this requirement, but it made tri arb very difficult in simply placing the orders because you had to determine the proper exchange rate to buy the binance coins, and if it changed then you were no longer purchasing 'whole' coins. This project started out pretty straightforwarded and then I started running into LOTS of unforeseen problems--like having to buy coins with whole binance coins!!
